use chrono::{DateTime, Utc};
use crate::{api_success_response_alias, dto::user_dto::{UserReadDto, ProfileUpdateDto}, paginated_response_alias, pagination_metadata_alias};
use crate::dto::token_dto::TokenReadDto;
use crate::dto::group_chat_dto::{GroupChatReadDto, GroupChatCreateDto, GroupChatUpdateDto};
use crate::dto::invitation_dto::{InvitationReadDto, InvitationCreateDto, InvitationUpdateStatusDto, InvitationUpdateResponseDto};
use crate::dto::group_membership_dto::{GroupMembershipReadDto, GroupMembershipCreateDto};
use crate::dto::text_message_dto::{TextMessageReadDto, TextMessageCreateDto};
use crate::response::{PaginatedResponse};

pub mod token_dto;
pub mod user_dto;
pub mod group_chat_dto;
pub mod invitation_dto;
pub mod group_membership_dto;
pub mod text_message_dto;
pub mod text_message_pagination_dto;

api_success_response_alias!(ApiSuccessResponseUserReadDto, UserReadDto);
api_success_response_alias!(ApiSuccessResponseUserUpdateDto, ProfileUpdateDto);
api_success_response_alias!(ApiSuccessResponseTokenReadDto, TokenReadDto);
api_success_response_alias!(ApiSuccessResponseGroupChatReadDto, GroupChatReadDto);
api_success_response_alias!(ApiSuccessResponseGroupChatCreateDto, GroupChatCreateDto);
api_success_response_alias!(ApiSuccessResponseGroupChatUpdateDto, GroupChatUpdateDto);
api_success_response_alias!(ApiSuccessResponseInvitationReadDto, InvitationReadDto);
api_success_response_alias!(ApiSuccessResponseInvitationUpdateDto, InvitationUpdateResponseDto);
api_success_response_alias!(ApiSuccessResponseGroupMembershipReadDto, GroupMembershipReadDto);
api_success_response_alias!(ApiSuccessResponseVecGroupMembershipReadDto, Vec<GroupMembershipReadDto>);
api_success_response_alias!(ApiSuccessResponseInvitationUpdateResponseDto, InvitationUpdateResponseDto);
api_success_response_alias!(ApiSuccessResponseVecInvitationReadDto, Vec<InvitationReadDto>);
api_success_response_alias!(ApiSuccessResponseTextMessageReadDto, TextMessageReadDto);
pagination_metadata_alias!(PaginationMetadataDateTime, DateTime<Utc>);
paginated_response_alias!(PaginatedTextMessageResponse, TextMessageReadDto, PaginationMetadataDateTime);
